### ISSUE TITLE
Using bootstrap.thumnail 

### ISSUE THREAD

**Issue by janeshdev** [jimhester/knitrBootstrap#170]
Hi, 

I am not sure how to use different bootstrap options in out knitr document. For example, I don't want the images to pop up so I would like to use bootstrap.thumbnail=FALSE. But don't know where to put that code. Is it on the top of the document where we specify the options ?

**Comment by jimhester** [comment]
In https://github.com/jimhester/knitrBootstrap#options it says

> See [Knitr Options](http://yihui.name/knitr/options/) for more about how to set the two different types of options.

`bootstrap.thumbnail` is a Chunk Option, so if you go to the Knitr Options page it mentions that Chunk Options are set at the start of a given chunk, so you would put `bootstrap.thumbnail=FALSE` at the start of the chunks you don't want to thumbnail.

However also on that page it mentions if you want to set a Chunk Option globally in a document, you can do so using `opts_chunk$set`, so to turn off thumbnails globally put the following in your setup chunk.

```r
opts_chunk$set(bootstrap.thumbnail=FALSE)
```
