### ISSUE TITLE
Scrolling of the menu / table of contents

### ISSUE THREAD

**Issue by janeshdev** [jimhester/knitrBootstrap#171]
Hi I have been using knitrBootstrap for a while now. As my document has began to get large, now it seems it requires a capability to make the navigation / table of contents the ability to scroll. As you can see in the image below, there are several other menu items that are not visible. I can look at the text by scrolling the whole text but I can't scroll the menu itself. Is there anyway to handle such cases ?

![navigation](https://cloud.githubusercontent.com/assets/3325086/6673561/70699594-cbd1-11e4-8b27-f4d75705d19b.png)

**Comment by jimhester** [comment]
This is the same issue as #34, there aren't really any great solutions I have found.
