### ISSUE TITLE
General package documentation listed as primerTree

### ISSUE THREAD

**Issue by BrianDiggs** [jimhester/knitrBootstrap#175]
The general package documentation has an entry of "primerTree" which does not seem to have any relevance to the package. This is due to the line https://github.com/jimhester/knitrBootstrap/blob/master/R/knit_bootstrap.R#L21. This causes the help page to be listed as "primerTree {knitrBootstrap}" and for it to appear in indexes as "primerTree" (see, for example, http://www.inside-r.org/packages/cran/knitrBootstrap/docs)

**Comment by jimhester** [comment]
Thank you, silly mistake by me!
