### ISSUE TITLE
d3heatmap with knitrBootstrap doesn't work

### ISSUE THREAD

**Issue by al2na** [jimhester/knitrBootstrap#176]
I'm not able to view d3heatmap heatmaps in knitrBootstrap documents. I'm using development version of knitrBootstrap and I use render() function as shown below.

```
rmarkdown::render("dump.Rmd","knitrBootstrap::bootstrap_document")
```

contents of the Rmd file:

    You can also embed plots, for example:

    ```{r}
     library(d3heatmap)
     d3heatmap(mtcars, scale = "column", colors = "Blues")
    ```

**Comment by humburg** [comment]
I just tested this with the latest development version (c2771fb) and this seems to work fine now.
