### ISSUE TITLE
rpivotTable is not getting drawn with this

### ISSUE THREAD

**Issue by KrishnaPG** [jimhester/knitrBootstrap#192]
This knitrBootstrap is not displaying the R HTML Widget https://github.com/smartinsightsfromdata/rpivotTable 

Normal 'html_document' output type is producing correctly.

Sample code to reproduce the problem:
````
---
output:
  knitrBootstrap::bootstrap_document:
    title: "Test file"
    theme: amelia
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

> 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

requiredPackages <- c('htmlwidgets', 'rpivotTable')

for(p in requiredPackages) {
  if(!is.element(p, .packages(all.available = TRUE)))    install.packages(p)
  library(p,character.only = TRUE)
}
```


```{r }
data(HairEyeColor)
rpivotTable(data = HairEyeColor, rows = "Hair",cols="Eye", vals = "Freq", aggregatorName = "Sum", rendererName = "Table", width="100%", height="400px")
```

````

**Comment by humburg** [comment]
This seems to work as expected with #68. Use `devtools::install_github('jimhester/knitrBootsrap', ref='rmarkdown_template')` to install the latest version.

**Comment by KrishnaPG** [comment]
Getting this error:

![image](https://cloud.githubusercontent.com/assets/4610831/16722031/7667b5fe-4761-11e6-8848-80d786e8b556.png)

**Comment by humburg** [comment]
Sorry, there was a typo in the repo name. Now fixed above.
