### ISSUE TITLE
custom css

### ISSUE THREAD

**Issue by frenkiboy** [jimhester/knitrBootstrap#197]
Is it possible to import a custom css file for header formatting?

    knitrBootstrap::bootstrap_document:
        css: header.css

gives the following error:

    Error in (function (title = NULL, theme = "default", highlight = "highlightjs",  : 
      unused argument (css = "header.css")
    Calls: <Anonymous> -> create_output_format -> do.call
    Execution halted

**Comment by jimhester** [comment]
You can use the `custom.header` option to provide any extra header logic like script or css includes.

But I would actually recommend you use `rmarkdown::html_document()`, which is more actively maintained.
