### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by jimhester** [jimhester/knitrBootstrap#38]
@kohske @jlehtoma @lcolladotor @khughitt @jjallaire,

  At some point in the past you expressed interest through questions or bug
reports about knitrBootstrap (https://github.com/jimhester/knitrBootstrap),
to produce Knitr HTML reports utilizing the Bootstrap HTML framework.  I have
recently done a major overhaul and rewrite of the package to generate Bootstrap HTML
tags directly using R rather than using javascript to modify the DOM as was done previously.
In addition the package now uses RStudio's new
[rmarkdown](http://rmarkdown.rstudio.com/) package to convert the HTML from
markdown and slightly modified the format of the pages in to make them
more consistent and less buggy.

  These changes have made the package both easier for me to maintain as well as
easier to enhance.  It should also be simpler to use in RStudio and along with
other output formats.  I would appreciate both your feedback on the new format
as well as any bugs or feature regressions you find so I can make changes and
fixes before submitting the updates to CRAN.

  Thank you for your (past) interest in my package, and I hope these changes improve
your experience!

Jim Hester

I apologize for this slight abuse of the github issue tracker, I did not have an email address to send this message to you!

**Comment by lcolladotor** [comment]
Hi,

We can probably close this issue, no? I just discovered https://github.com/issues/mentioned today and this is my 2nd oldest one hehe.

Best,
Leo

**Comment by khughitt** [comment]
I think it's safe to close.. Can always file new issues if related problems arise in the future.
